# \n (new line)
print("line A\nline B\n line C")
# \t (tab))
print("name\tAnushka") 
# \\ (blackslash)
print("this is a blackslash\\")
print("this is blackslash\\\\")
# \b (backspace)
print("hell\blo")